add quotes to prevent globbing

diff --git a/check-remote b/check-remote
--- a/check-remote
+++ b/check-remote
@@ -10,16 +10,14 @@ clean_up() {
   git merge --abort > /dev/null
 }
 
-
-
 (git merge HEAD || clean_up) > /dev/null
 git pull --ff-only > /dev/null
-if ! git config remote.$1.url > /dev/null; then
-  git remote add $1 git@git.dn42:$1/registry.git
+if ! git config "remote.$1.url" > /dev/null; then
+  git remote add "$1" "git@git.dn42:$1/registry.git"
 fi
-git fetch $1 2> /dev/null
-git merge --no-ff --no-commit $1/$2 2> /dev/null
-./check-pol HEAD $3 2> /dev/null || (echo "Policy Check FAILED"; clean_up; exit 1)
-./check-my-stuff $3 2> /dev/null || (echo "Schema Check FAILED"; clean_up; exit 1)
+git fetch "$1" 2> /dev/null
+git merge --no-ff --no-commit "$1/$2" 2> /dev/null
+./check-pol HEAD "$3" 2> /dev/null || (echo "Policy Check FAILED"; clean_up; exit 1)
+./check-my-stuff "$3" 2> /dev/null || (echo "Schema Check FAILED"; clean_up; exit 1)
 echo OK
 clean_up
