Revert "initial commit"
This reverts commit 29de9ea44241b2f459e0d589368c87e9cac4e9e3.

diff --git a/check-my-stuff b/check-my-stuff
--- a/check-my-stuff
+++ b/check-my-stuff
@@ -11,9 +11,9 @@ BASE="$(dirname "$BASE")"
 cd "$BASE" || exit 1
 
 if [ "$1" = "--all" ]; then
-    utils/schema-check/dn42-schema.py -vv scan data/ || ( echo "Schema validation failed, please check above!" ; exit 1 )
+    utils/schema-check/dn42-schema.py -v scan data/ || ( echo "Schema validation failed, please check above!" ; exit 1 )
 else
-    utils/schema-check/dn42-schema.py -vv scan data/ -f "data/mntner/$1" || ( echo "Schema validation for mntner object failed, please check above!" ; exit 1 )
-    utils/schema-check/dn42-schema.py -vv scan data/ -m "$1" || ( echo "Schema validation for related objects failed, please check above!" ; exit 1 )
+    utils/schema-check/dn42-schema.py -v scan data/ -f "data/mntner/$1" || ( echo "Schema validation for mntner object failed, please check above!" ; exit 1 )
+    utils/schema-check/dn42-schema.py -v scan data/ -m "$1" || ( echo "Schema validation for related objects failed, please check above!" ; exit 1 )
 fi
 
